# Generated by Django 3.2.11 on 2023-12-25 04:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('fi', 'Fiction'), ('sc-tech', 'Science & Technology'), ('po', 'Poetry'), ('his', 'History'), ('pol', 'Polotics'), ('phi', 'Philosophy'), ('phys', 'Psycology'), ('sh', 'Self Help')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger'), ('his', 'History'), ('pol', 'Polotics'), ('phi', 'Philosophy'), ('phys', 'Psycology'), ('sh', 'Self Help')], default='timwzone.now', max_length=100),
            preserve_default=False,
        ),
    ]
