# Generated by Django 3.2.11 on 2023-12-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0002_auto_20231225_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default=1, upload_to='book_image/'),
            preserve_default=False,
        ),
    ]
